---

- hosts: all
  become: yes
  tasks: 
  

  - name: Update Repo index Install apache2 package and support package
    apt:
      update_cache: yes
      name: 
        apache2
        libapache2-mod-php
      state: latest
    when: ansible_distribution == "Ubuntu"




  - name: Update Repository Index Install apache2 package and support pacakge
    dnf:
      update_cache: yes
      name: 
        httpd
        php
      state: latest
    when: ansible_distribution == "Oracle Linux"



